version: '3.7'

services:
  app:
    image: app
    container_name: app
    restart: always
    user: cronbot
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.app.schedule: "@every 10s"
      ofelia.job-exec.app.command: "Rscript app/hello.R"
      ofelia.job-exec.app.slack-webhook: ${SLACK_URL_BOT}

  ofelia:
    image: mcuadros/ofelia:latest
    restart: always
    depends_on:
      - app
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
