version: '3.7'

services:
  app:
    image: app
    container_name: app
    restart: always
    user: ${USER}
    build:
      context: .
      dockerfile: dockerfile-app
      args:
          - http_proxy
          - https_proxy
          - HTTP_PROXY
          - HTTPS_PROXY
    labels:
      ofelia.enabled: "true"
      # Set the schedule for your job
      ofelia.job-exec.app.schedule: "@every 15m"
      # Run this script on the above schedule
      ofelia.job-exec.app.command: "Rscript app.R"
      ofelia.job-exec.no-overlap: "true"
      ofelia.job-exec.app.slack-webhook: ${SLACK_URL_BOT}

  ofelia:
    image: mcuadros/ofelia:latest
    restart: always
    depends_on:
      - app
    command: daemon --docker
    environment:
        - http_proxy
        - https_proxy
        - HTTP_PROXY
        - HTTPS_PROXY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
